### ISSUE TITLE
ctf challenge verify

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/ctfcli#101]
We should have a way to have ctfcli verify that a given installed challenge matches the local state. This could help in situations where perhaps an admin deletes files or changes a description.

**Comment by reteps** [comment]
+ 1 on this issue. An option, e.g. `ctf challenge pull`, to get changes (e.g. if the CTFd state and repo state have diverged) from CTFd and make the corresponding changes in the challenge.yml files would also be nice.
