### ISSUE TITLE
Deployment fails if site password is set

### ISSUE THREAD

**Issue by pl4nty** [CTFd/ctfcli#111]
`ctf challenge sync`, `install` and `deploy` fail if a site password is configured. I noticed a `site_password` cookie is sent in the web UI though, and manual API calls succeed with it (eg `curl`)

**Comment by ColdHeat** [comment]
Yes the site password is transmitted via a cookie. However there isn't currently any UI to set those cookies in ctfcli. For the time being I would disable the password and disable registration so no one can login to the authenticated parts.

**Comment by pl4nty** [comment]
Yeah, I ended up disabling the password. I'm happy PR a feature for this if you want? Maybe something like
```python
if config["config"]["site_password"]:
  s.cookies["site_password"] = config["config"]["site_password"]
```
https://github.com/CTFd/ctfcli/blob/45ffa11f613feb6d279c01fee4c83b5f6fd074e7/ctfcli/utils/config.py#L82-L83

**Comment by ColdHeat** [comment]
Sure a PR wolud be great! However, I would prefer a more generic solution to the problem instead of specific keys. Perhaps if you could define an entire cookies sub-section or a cookies dictionary?

**Comment by pl4nty** [comment]
Looks like ConfigParser doesn't parse `[config.xyz]`, `cookies = {'site_password': 'password'}`, or `cookies['site_password'] = 'password'`, so I used a separate `[cookies]` section instead
