### ISSUE TITLE
Allow `connection_info` for container challenges

### ISSUE THREAD

**Issue by pl4nty** [CTFd/ctfcli#120]
`connection_info` for container challenges is currently set by the deployment handler. It would be helpful to be able to override this in `challenge.yml` for certain challenges.

https://github.com/CTFd/ctfcli/blob/de3dcee5aef90d2b3a02f2625a623e3e6914903d/ctfcli/cli/challenges.py#L340

**Comment by ColdHeat** [comment]
Makes sense, feel free to submit a PR for this if you can. I think if specified the connection info in challenge.yml should take priority.
