### ISSUE TITLE
PyYAML installation error

### ISSUE THREAD

**Issue by Killuak11** [CTFd/ctfcli#124]
Anyone else getting an error when using `pip install ctfcli`?
Mine returns errors when trying to build wheel.

`Collecting pyyaml==5.4 (from ctfcli)
  Using cached PyYAML-5.4.tar.gz (174 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-7195v9fj/overlay/local/lib/python3.10/dist-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************`

**Comment by ColdHeat** [comment]
Yeah I think this was related to the new Cython release that broke PyYAML. I will put up a version bump for PyYAML shortly.

**Comment by Killuak11** [comment]
Awesome Sauce. Thanks a bunch
