### ISSUE TITLE
Support CTFd site password

### ISSUE THREAD

**Issue by TheNewJavaman** [CTFd/ctfcli#152]
Installing a challenge to a CTFd instance with a site password returns a HTTP 401 error.

### Temporary fix

Edit `site_password` cookie in `.ctf/config`

```
[config]
url = https://my-instance.ctfd.io
access_token = ctfd_mytoken

[cookies]
site_password = my_site_password

[challenges]
```

### Proposed solution

Add field `site_password`

```
[config]
url = https://my-instance.ctfd.io
access_token = ctfd_mytoken
site_password = my_site_password

[challenges]
```

I forked and am working on the proposed solution

**Comment by pl4nty** [comment]
The cookies section is deliberately separate https://github.com/CTFd/ctfcli/issues/111

**Comment by ColdHeat** [comment]
I think the current solution is acceptable until the config file is entirely restructured.
