### ISSUE TITLE
Install and Sync all commands

### ISSUE THREAD

**Issue by jimender2** [CTFd/ctfcli#23]
Add a command to install and Sync commands that allow you install all challenges in a specified directory. Allowing it to loop through the directories recursively would be nice too.  That way I can store my challenges in different directories based on category.

IE: I would run ctf challenge install Challenges

where the challenges folder looks like this.
Challenges
    Crypto
        rsa1
            challenge.yml
        rsa2
             challenge.yml
     Binary
         intoverflow
             challenge.yml
         bufferoverflow
             challenge.yml
...

**Comment by ColdHeat** [comment]
While this is being worked on you can usually use something like `ls -1 | xargs -L 1 ctf challenge install` to run on all directories in the current dir.
