### ISSUE TITLE
Flag Case Sensitivity

### ISSUE THREAD

**Issue by nopresearcher** [CTFd/ctfcli#32]
Add the ability to specify 'Case Insensitive' flags in the spec.

**Comment by ColdHeat** [comment]
I believe you can specify this by specifying the direct JSON that's posted up to the API. https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml#L29-L33

I believe you can put `case_insensitive` in the data section but that's just off the top of my head.

**Comment by ColdHeat** [comment]
If anything this should be an improvement to the reference yaml but I'm not sure about adding a new yaml field for data.

**Comment by ColdHeat** [comment]
Since I had to do this myself recently here is how you do it:

```
flags:
    - stuff
    - {
        type: "regex",
        content: "(.*)STUFF(.*)",
        data: "case_insensitive",
    }
```
