### ISSUE TITLE
Support existing git repositories

### ISSUE THREAD

**Issue by obilodeau** [CTFd/ctfcli#34]
We are a monthly event and we already host our challenges in a git repo even when not using CTFd: https://github.com/montrehack/challenges

It would be nice if `ctfcli` would have detected that it was already in a git tree and wouldn't do anything about it. For now, I'm going to create a distinct repo for our event but I wanted to let you know of that use case.

This tool is a very nice addition to the CTFd ecosystem by the way! Thanks!

**Comment by ColdHeat** [comment]
Hi do you mean that we should skip the git init command? The way we use ctfcli each "event" is a seperate repo but having multiple "events" in a single repo can make sense. I could add a command to skip git init or an input to allow for skipping.

I don't think the project is ready to do multiple events per repo though, it's not structured that way just yet.

**Comment by obilodeau** [comment]
Only one event is active at a time so I think that skipping the `git init` might be enough. Yes.
