### ISSUE TITLE
Visible and Hidden states reversed

### ISSUE THREAD

**Issue by chasit** [CTFd/ctfcli#46]
When creating a new challenge (blank) the state of the challenge is by default set to "Hidden".

Upon adding and installing the challenge and opening CTFd the challenge will be "Visible" and not "Hidden" as per the challenge.yml.
When changing the state in the challenge.yml to "Visible" (and syncing the change) the challenge  will be set to "Hidden" in CTFd.

**Comment by chasit** [comment]
This only seems to be happening when installing a challenge for the first time, when syncing the correct state will be applied.

**Comment by ColdHeat** [comment]
I couldn't reproduce this and I think there were other issues that mentioned this and I believe they were resolved. I'm putting up #54 to clarify how the state field works but I believe this should already be patched. Try out the latest release or the code from Github and if the issue still happens feel free to commend back.
