### ISSUE TITLE
Use of markdown in challenge description

### ISSUE THREAD

**Issue by arnaudruffin** [CTFd/ctfcli#49]
Hi!

Maybe i'm missing something but I couldn't find how to use the standard markdown syntax in the `description` field of the challenge file. If I try to use multiline syntaxe for yaml it seems that every special char is escaped.

Could you provide an example ?
Thanks

**Comment by ColdHeat** [comment]
I don't remeber exactly how this is done off the top of my head but I believe something like this should work:

```
--- 
description: "# asdf"

```

Perhaps try throwing your yaml into http://www.yamllint.com/? 

I haven't tried this myself just yet but I can update the issue if I run into something.

**Comment by arnaudruffin** [comment]
Hi!
I've tried the multiline syntax again and it seems to work... I've must have done something wrong on my first try.
Anyway: this works:

```yaml
description:  | 
    # Title 1
    ## Title 2
    ### Title 3
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque posuere dui molestie, ullamcorper arcu nec, maximus nulla. Vestibulum placerat, nisi iaculis venenatis vehicula, magna libero facilisis neque, vitae consectetur enim lectus nec tortor. Vivamus ac venenatis mauris. Duis eu finibus mi. Vestibulum sodales neque et mi commodo, sit amet egestas ex fermentum. Ut pretium arcu massa, id suscipit tellus euismod et."
```
Thanks for the help
