### ISSUE TITLE
Add a command to create dir structure from an existing installation

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/ctfcli#6]
Something to pull down all the data from a given CTFd instance.

**Comment by jarrault** [comment]
Hey, I would like to work on this feature :smiley: 

But to be sure on what the feature will look like, I want to understand if the command will only be accessible by the admins ?
I think it would be great to use the CLI as a user. This mean the "init" command can also ask for a user token and so on ...

What do you think of this ?

**Comment by ColdHeat** [comment]
Glad that you're going to take it on!

Technically there's no way to restrict it entirely to admins because users can view challenges via the API as well. However only admins can view sensitive things like all flags, tags, hints, etc. 

I don't think that ctfcli should be useable for a user to archive the entire CTF because it would just have incomplete data. The admin should be able to use ctfcli to generate the ctf directory though which is the intention of this issue.

**Comment by jarrault** [comment]
Thanks for your answer, I will try to implement it.

**Comment by reteps** [comment]
Closed by #134

**Comment by ColdHeat** [comment]
Indeed it is. See `ctf challenge mirror` and `ctf challenge mirror --create`. 

Closed by #134
