### ISSUE TITLE
I am completely rewriting ctfcli for a personal project and I wanted to share it here

### ISSUE THREAD

**Issue by mister-hai** [CTFd/ctfcli#73]
I am making an "all in one" setup script using docker-compose and kubernetes with some bash and python tying it all together to make a CTFd based pentesting/malware analysis/threat actor analysis/learning project thing-a-ma-bob for my community to learn with but I needed to integrate ctfcli into the overall schema and ended up rewriting it...

I am integrating as many open source challenges as I can into the repository, it is a repository manager with ctfd/git operations that interfaces with the CTFd server. It has a masterlist yaml file that is a representation of the entire challenge set.

I have yet to fully morph the API calls to ctfd into a more abstract schema but I think you should just see it.

I have gotten the masterlist for the challenge repository working, it has read/write methods that turn code to yaml, I am now working on the getter/setter/listing methods, I am going to also get the templating and "build a challenge on the command line" thing going, 

The root of the repository is here
https://github.com/mister-hai/sandboxy/tree/master/data/CTFd

the tool itself is here
https://github.com/mister-hai/sandboxy/tree/master/data/CTFd/ctfcli

And the modified open source challenges are in the "challenges" folder

I didnt know how to inform anyone of this properly, I just an trying to contribute to both of our communities and provide a platform for accelerated learning. I am trying very hard to document everything as well as I would have appreciated when I was learning the beginner stuff... I still am learning newb stuff lmao!

Thank you for your time!

**Comment by ColdHeat** [comment]
Hi there, I think it would be better if you PR'ed changed into ctfcli so there's less duplicated work but good luck with your project!
